---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# Run some antsibull-docs 1.8.0 tests against the current development version of antsibull-core
# to make sure we don't accidentally break compatibility.

name: antsibull-docs compatibility

on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
    branches:
      - main
      - stable-*
  # Run once per week (Monday at 04:00 UTC)
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out antsibull-core
        uses: actions/checkout@v4
        with:
          path: antsibull-core

      - name: Checkout antsibull-docs-parser main
        uses: actions/checkout@v4
        with:
          repository: ansible-community/antsibull-docs-parser
          ref: main
          path: antsibull-docs-parser

      - name: Check out dependent project antsibull-fileutils
        uses: actions/checkout@v4
        with:
          repository: ansible-community/antsibull-fileutils
          path: antsibull-fileutils

      # nb: this is the first version of antsibull-docs that declares support
      # for antsibull-core v3.
      - name: Check out antsibull-docs main
        uses: actions/checkout@v4
        with:
          repository: ansible-community/antsibull-docs
          ref: 2.9.0
          path: antsibull-docs

      - name: Patch antsibull-docs noxfile.py
        run: |
          sed -i noxfile.py -e 's/args = ("antsibull-core", "antsibull-docs-parser")/args = ("antsibull-core", "antsibull-docs-parser", "antsibull-fileutils")/g'
        working-directory: antsibull-docs

      - name: Set up Python 3.12
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        env:
          PYTHON: "${{ steps.python.outputs.python-path }}"
        run: |
          pipx install --python "${PYTHON}" nox
          python -m venv venv
          . ./venv/bin/activate
          python -m pip install . ../antsibull-core ../antsibull-docs-parser ../antsibull-fileutils
        working-directory: antsibull-docs

      - name: Run type checkers
        run: |
          nox -e typing
        working-directory: antsibull-docs

      - name: Use antsibull-docs sphinx-init
        run: |
          . ./venv/bin/activate
          antsibull-docs sphinx-init --lenient --dest-dir . --use-current --sphinx-theme sphinx_rtd_theme
        working-directory: antsibull-docs

      - name: Install dependencies
        run: |
          . ./venv/bin/activate
          pip install ansible-core -r requirements.txt
        working-directory: antsibull-docs

      - name: Install collections
        run: |
          . ./venv/bin/activate
          ansible-galaxy collection install 'community.docker:==3.0.0' 'sensu.sensu_go:==1.14.0'
          git clone https://github.com/ansible-collections/community.crypto.git ~/.ansible/collections/ansible_collections/community/crypto --branch 2.15.0
        working-directory: antsibull-docs

      - name: Lint collection docs
        run: |
          . ./venv/bin/activate
          antsibull-docs lint-collection-docs ~/.ansible/collections/ansible_collections/community/docker
        working-directory: antsibull-docs

      - name: Build docsite
        run: |
          . ./venv/bin/activate
          ./build.sh
        working-directory: antsibull-docs
